import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { BsStars } from "react-icons/bs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-red-300 flex justify-between px-10 py-4">
          <Link href="/">
            <h1 className="flex items-center">
              <BsStars />
              GiaLog
            </h1>
          </Link>
          <nav className="flex gap-4">
            <Link href="/about">ABOUT</Link>
            <Link href="/posts">POSTS</Link>
            <Link href="/contact">CONTACT</Link>
          </nav>
        </header>
        <main className="min-h-screen flex flex-col gap-4 px-10 py-6">
          {children}
        </main>
        <footer className="bg-slate-400 py-2 text-center">footer</footer>
      </body>
    </html>
  );
}
